// Generated by scripts/generate-razavi-symbol-catalog.mjs. Do not edit.
import type { SymbolDefinition } from "./schema.js";
import type {
  RazaviSemanticPrimitiveEntry,
  RazaviSymbolCatalogEntry,
} from "./razavi-catalog.js";

export const razaviSymbolCatalogIdentity = {
  schemaVersion: 2,
  id: "razavi-symbols",
  version: 1,
} as const;

export const razaviSymbolCatalogEntries: readonly RazaviSymbolCatalogEntry[] = [
  {
    symbolId: "capacitor",
    name: "Capacitor",
    category: "passive",
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: ["spice:C"],
    assetPath: "capacitor.symbol.json",
    assetHash:
      "e5072a4d36017918f5410d73f3b29536bf3637689295c9e9f941928553ac481b",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/capacitor-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/capacitor-geometry.json",
    },
  },
  {
    symbolId: "current-source",
    name: "Independent Current Source",
    category: "source",
    reviewStatus: "reviewed",
    pinOrder: ["+", "-"],
    palette: true,
    automaticMappings: ["spice:I"],
    assetPath: "current-source.symbol.json",
    assetHash:
      "26427f16b5e60f7100d80c086747b2ce832a869e551dac5249f13ccb43722673",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/current-port-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/current-port-geometry.json",
    },
    generation: {
      kind: "razavi-raster-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      converterPath: "scripts/generate-razavi-peripheral-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "diode",
    name: "Diode",
    category: "passive",
    reviewStatus: "reviewed",
    pinOrder: ["A", "K"],
    palette: true,
    automaticMappings: ["spice:D"],
    assetPath: "diode.symbol.json",
    assetHash:
      "3b6d9ec0ae5e4e9d5c9177acb953dd9afb1899944aa9bb42ad7dade609a87f82",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/diode-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/diode-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/diode-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "ground",
    name: "Ground",
    category: "power",
    reviewStatus: "reviewed",
    pinOrder: ["0"],
    palette: true,
    automaticMappings: [],
    assetPath: "ground.symbol.json",
    assetHash:
      "8aa38b7c438675e1dcb161b57be65d62609fe544e9ba19fc411e19f6c56a43e8",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/peripheral-geometry.json",
    },
    generation: {
      kind: "razavi-raster-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      converterPath: "scripts/generate-razavi-peripheral-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "ideal-switch",
    name: "Ideal Switch",
    category: "switch",
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Two-terminal Razavi switch; SPICE S has a four-terminal control contract.",
    assetPath: "ideal-switch.symbol.json",
    assetHash:
      "9cdce6cc5418f516626497c272dd2753b04fa916fdc1c699bdc4230b4772b718",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/ideal-switch-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/ideal-switch-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/ideal-switch-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "inductor",
    name: "Inductor",
    category: "passive",
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: ["spice:L"],
    assetPath: "inductor.symbol.json",
    assetHash:
      "a0e4bf19ef973f7fcbe184e568f691c4986ca8517aa2623eb06c633c070ebe10",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/inductor-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/inductor-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/inductor-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/inductor-vector-source.json",
      converterPath: "scripts/generate-razavi-inductor-asset.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "nmos",
    name: "NMOS",
    category: "transistor",
    reviewStatus: "reviewed",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/mos-geometry.json",
    },
    pinOrder: ["D", "G", "S", "B"],
    palette: true,
    automaticMappings: ["spice:M:nmos", "pdk:model-type:nmos"],
    assetPath: "nmos.symbol.json",
    assetHash:
      "62fe9007af3b1c163e617b50a16c31075b621b3201c0f81a43f466d4e04133eb",
  },
  {
    symbolId: "nmos3",
    name: "NMOS (3-terminal)",
    category: "transistor",
    reviewStatus: "provisional",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/mos-geometry.json",
    },
    pinOrder: ["D", "G", "S"],
    palette: true,
    automaticMappings: [],
    assetPath: "nmos3.symbol.json",
    assetHash:
      "93636dfafd0690edaa7a9402e3bc2da014d048a404a558e8d3765c3c30126cc8",
  },
  {
    symbolId: "npn",
    name: "NPN Bipolar Transistor",
    category: "transistor",
    reviewStatus: "reviewed",
    pinOrder: ["C", "B", "E"],
    palette: true,
    automaticMappings: ["spice:Q:npn", "pdk:model-type:npn"],
    assetPath: "npn.symbol.json",
    assetHash:
      "07be0cd5b1b774d99c069117e6369e35d4dbc5da248ca15632c98da0622ce094",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/npn-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/npn-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/npn-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "opamp",
    name: "Operational Amplifier",
    category: "analog-block",
    reviewStatus: "reviewed",
    pinOrder: ["IN+", "IN-", "OUT"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Three-terminal textbook op-amp; SPICE subcircuit pin and supply contracts require an explicit PDK mapping.",
    assetPath: "opamp.symbol.json",
    assetHash:
      "0710b34aa1ae4f39d555155bfc51e66495cf6b0b02ae094707a41df8733e4ee3",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/opamp-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/opamp-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/opamp-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/opamp-vector-source.json",
      converterPath: "scripts/generate-razavi-opamp-asset.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "pmos",
    name: "PMOS",
    category: "transistor",
    reviewStatus: "reviewed",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/mos-geometry.json",
    },
    pinOrder: ["D", "G", "S", "B"],
    palette: true,
    automaticMappings: ["spice:M:pmos", "pdk:model-type:pmos"],
    assetPath: "pmos.symbol.json",
    assetHash:
      "a995e33e91c8c4828967e75572cb323fdcd6af49a710dd088a2b5d5b3e91e391",
  },
  {
    symbolId: "pmos3",
    name: "PMOS (3-terminal)",
    category: "transistor",
    reviewStatus: "provisional",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/mos-geometry.json",
    },
    pinOrder: ["D", "G", "S"],
    palette: true,
    automaticMappings: [],
    assetPath: "pmos3.symbol.json",
    assetHash:
      "d2416d0a22a651dbac75d94bfa57c63aa1a792dc88e275256f066ad9717165ba",
  },
  {
    symbolId: "pnp",
    name: "PNP Bipolar Transistor",
    category: "transistor",
    reviewStatus: "reviewed",
    pinOrder: ["C", "B", "E"],
    palette: true,
    automaticMappings: ["spice:Q:pnp", "pdk:model-type:pnp"],
    assetPath: "pnp.symbol.json",
    assetHash:
      "9995cb8ff67a74dbe42da38e755b3df17a5f48f6082426d710273fcd8cdfc0c8",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/pnp-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/pnp-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/pnp-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "port",
    name: "Port",
    category: "interface",
    reviewStatus: "reviewed",
    pinOrder: ["P"],
    palette: true,
    automaticMappings: [],
    assetPath: "port.symbol.json",
    assetHash:
      "d0ca494905a2975920898719f15c59d35be44c85f627308b8bfadccc549707ab",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/current-port-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/current-port-geometry.json",
    },
  },
  {
    symbolId: "port-filled",
    name: "Filled Port",
    category: "interface",
    reviewStatus: "reviewed",
    pinOrder: ["P"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Explicit solid endpoint style; no automatic SPICE mapping.",
    assetPath: "port-filled.symbol.json",
    assetHash:
      "bb266895c22ed004c7706ca7c3825e84f51bcd78b00f000b4a47830cc1e0ab12",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/current-port-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/current-port-geometry.json",
    },
  },
  {
    symbolId: "resistor",
    name: "Resistor",
    category: "passive",
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: ["spice:R"],
    assetPath: "resistor.symbol.json",
    assetHash:
      "474648eca063d107fb39f641a6ce6b3a99c2b5bd4d26f6ebff926cccd184c0a7",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/passive-geometry.json",
    },
  },
  {
    symbolId: "transformer",
    name: "Transformer / Coupled Inductor",
    category: "passive",
    reviewStatus: "reviewed",
    pinOrder: ["P1", "P2", "S1", "S2"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Textbook four-terminal visual composite; SPICE K references existing inductors rather than owning four nodes.",
    assetPath: "transformer.symbol.json",
    assetHash:
      "e0df6c64f87711989aea3f6761c12fcd75ac1e17cb320743a98c8ace5ba6d6a7",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/transformer-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/transformer-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/transformer-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "vccs",
    name: "Voltage-Controlled Current Source",
    category: "source",
    reviewStatus: "reviewed",
    pinOrder: ["OUT+", "OUT-", "CTRL+", "CTRL-"],
    palette: true,
    automaticMappings: ["spice:G"],
    assetPath: "vccs.symbol.json",
    assetHash:
      "a64b5a3676fb48d24acf94225e491b3fac8b18e40475f80cdcbf8508d08a9e68",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/vccs-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/vccs-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/vccs-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "vdd",
    name: "VDD Power Port",
    category: "power",
    reviewStatus: "reviewed",
    pinOrder: ["P"],
    palette: true,
    automaticMappings: [],
    assetPath: "vdd.symbol.json",
    assetHash:
      "bf4571ccb9a15ecf6f60455b787d7919e783deae715fa324eec0609779c71cc6",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/vdd-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/vdd-geometry.json",
    },
  },
  {
    symbolId: "voltage-amplifier",
    name: "Voltage Amplifier",
    category: "analog-block",
    reviewStatus: "reviewed",
    pinOrder: ["IN", "OUT"],
    palette: true,
    automaticMappings: [],
    manualOnlyReason:
      "Textbook gain block has implicit reference nodes and no exact primitive SPICE terminal contract.",
    assetPath: "voltage-amplifier.symbol.json",
    assetHash:
      "42bd3e0e3740536979a04b9ecb0a26f8509674bd59538e4003b6cb059ebc253c",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/voltage-amplifier-vector-source.json",
        "fixtures/visual-reference/razavi-reference-v1/voltage-amplifier-reference.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/common-symbol-geometry.json",
    },
    generation: {
      kind: "razavi-pdf-vector-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/voltage-amplifier-vector-source.json",
      converterPath: "scripts/generate-razavi-common-assets.mjs",
      converterVersion: 1,
    },
  },
  {
    symbolId: "voltage-source",
    name: "Independent Voltage Source",
    category: "source",
    reviewStatus: "reviewed",
    pinOrder: ["+", "-"],
    palette: true,
    automaticMappings: ["spice:V"],
    assetPath: "voltage-source.symbol.json",
    assetHash:
      "33082df048526fd6520fe5c69ef9b7f4e6ef04dce29528688b5753a90e621590",
    visualAuthority: {
      kind: "razavi-reference-v1",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePaths: [
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      ],
      calibrationPath:
        "fixtures/visual-reference/razavi-reference-v1/peripheral-geometry.json",
    },
    generation: {
      kind: "razavi-raster-reference",
      referenceManifestPath:
        "fixtures/visual-reference/razavi-reference-v1/manifest.json",
      referencePath:
        "fixtures/visual-reference/razavi-reference-v1/razavi-six-panel.png",
      converterPath: "scripts/generate-razavi-peripheral-assets.mjs",
      converterVersion: 1,
    },
  },
];

export const razaviSemanticPrimitives: readonly RazaviSemanticPrimitiveEntry[] =
  [
    {
      id: "junction-dot",
      disposition: "semantic-primitive",
      geometry: {
        kind: "circle",
        sourceDiameterIU: 0.0787401574803157,
        fill: "foreground",
        stroke: "none",
      },
      runtimeOwner: "presentation.nodes.junction",
    },
  ];

export const razaviCatalogSymbols: readonly SymbolDefinition[] = [
  {
    schemaVersion: 1,
    id: "capacitor",
    name: "Capacitor",
    viewBox: {
      x: -12,
      y: -24,
      width: 24,
      height: 48,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: 0,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 0,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: 6.448819,
          y: -2.322992,
        },
        to: {
          x: -6.448819,
          y: -2.322992,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 6.448819,
          y: 2.322992,
        },
        to: {
          x: -6.448819,
          y: 2.322992,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -2.322992,
        },
        to: {
          x: 0,
          y: -20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: 2.606457,
        },
        to: {
          x: 0,
          y: 20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: [],
  },
  {
    schemaVersion: 1,
    id: "current-source",
    name: "Independent Current Source",
    viewBox: {
      x: -15,
      y: -24,
      width: 30,
      height: 48,
    },
    pins: [
      {
        name: "+",
        role: "positive",
        at: {
          x: 0,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "-",
        role: "negative",
        at: {
          x: 0,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "circle",
        center: {
          x: 0,
          y: 0,
        },
        radius: 10.755814,
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -6.976744,
        },
        to: {
          x: 0,
          y: -2.325581,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: 0,
            y: 6.976744,
          },
          {
            x: -4.651163,
            y: -2.325581,
          },
          {
            x: 4.651163,
            y: -2.325581,
          },
        ],
        fill: "foreground",
        stroke: "none",
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -10.755814,
        },
        to: {
          x: 0,
          y: -20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: 10.755814,
        },
        to: {
          x: 0,
          y: 20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: ["dc-current"],
  },
  {
    schemaVersion: 1,
    id: "diode",
    name: "Diode",
    viewBox: {
      x: -34,
      y: -14,
      width: 68,
      height: 28,
    },
    pins: [
      {
        name: "A",
        role: "anode",
        at: {
          x: -30,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 15,
        },
      },
      {
        name: "K",
        role: "cathode",
        at: {
          x: 30,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 15,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -30,
          y: 0,
        },
        to: {
          x: -10,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -10,
            y: -9,
          },
          {
            x: -10,
            y: 9,
          },
          {
            x: 7,
            y: 0,
          },
        ],
        fill: "foreground",
        stroke: "none",
      },
      {
        kind: "line",
        from: {
          x: 8,
          y: -10,
        },
        to: {
          x: 8,
          y: 10,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 8,
          y: 0,
        },
        to: {
          x: 30,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: ["pn-diode", "rectifier-diode"],
  },
  {
    schemaVersion: 1,
    id: "ground",
    name: "Ground",
    viewBox: {
      x: -12,
      y: -14,
      width: 24,
      height: 31,
    },
    pins: [
      {
        name: "0",
        role: "ground",
        at: {
          x: 0,
          y: -10,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: 0,
          y: -10,
        },
        to: {
          x: 0,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -6.395349,
          y: 0,
        },
        to: {
          x: 6.395349,
          y: 0,
        },
        style: {
          strokeRole: "ground",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -4.069767,
          y: 5.813953,
        },
        to: {
          x: 4.069767,
          y: 5.813953,
        },
        style: {
          strokeRole: "ground",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -2.325581,
          y: 11.046512,
        },
        to: {
          x: 2.325581,
          y: 11.046512,
        },
        style: {
          strokeRole: "ground",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: ["gnd"],
    labelVisibility: "hidden",
  },
  {
    schemaVersion: 1,
    id: "ideal-switch",
    name: "Ideal Switch",
    viewBox: {
      x: -34,
      y: -18,
      width: 68,
      height: 36,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: -30,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 15,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 30,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 15,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -30,
          y: 0,
        },
        to: {
          x: -11,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "circle",
        center: {
          x: -9,
          y: 0,
        },
        radius: 2,
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "circle",
        center: {
          x: 9,
          y: 0,
        },
        radius: 2,
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 11,
          y: 0,
        },
        to: {
          x: 30,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -7.5,
          y: -1.5,
        },
        to: {
          x: 7.5,
          y: -12,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: ["switch-open", "two-terminal-switch"],
  },
  {
    schemaVersion: 1,
    id: "inductor",
    name: "Inductor",
    viewBox: {
      x: -15,
      y: -32,
      width: 30,
      height: 64,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: 0,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 0,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "path",
        data: "M 0 -30 L 0 -29.243 C 0 -29.243 0 -29.243 0 -27.3261 C 0 -25.4114 0 -21.5777 0 -19.663 C 0 -17.7462 0 -17.7462 0 -17.7462 C 0 -17.7462 0 -17.7462 1.86778 -17.3623 C 3.73333 -16.9785 7.46443 -16.2131 9.28089 -14.6801 C 11.0974 -13.147 10.9969 -10.8485 7.26583 -9.31325 C 3.5325 -7.78019 -3.83152 -7.01478 -7.51353 -8.16402 C -11.1955 -9.31325 -11.1955 -12.3816 -7.46443 -13.0801 C -3.7311 -13.7808 3.73333 -12.1138 7.53138 -9.58103 C 11.3317 -7.04826 11.4633 -3.64965 7.73222 -1.4159 C 3.99888 0.815621 -3.59944 1.88229 -7.39749 0.882566 C -11.1955 -0.117155 -11.1955 -3.18326 -7.39749 -3.94868 C -3.59944 -4.71632 3.99888 -3.18326 7.69874 -0.683961 C 11.3986 1.81534 11.1978 5.28089 7.39749 7.58159 C 3.59944 9.88006 -3.79805 11.0137 -7.49791 10.0474 C -11.1955 9.08117 -11.1955 6.01506 -7.49791 5.06443 C -3.79805 4.11604 3.59944 5.28089 7.33277 7.19777 C 11.0639 9.11464 11.1308 11.7813 9.29875 13.4974 C 7.46443 15.2134 3.73333 15.9788 1.86778 16.3626 C 0 16.7464 0 16.7464 0 16.7464 C 0 16.7464 0 16.7464 0 18.8285 C 0 20.9105 0 25.0767 0 27.1609 C 0 29.243 0 29.243 0 29.243 L 0 30",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "round",
        },
      },
    ],
    variants: [],
    aliases: ["coil"],
  },
  {
    schemaVersion: 1,
    id: "nmos",
    name: "NMOS",
    viewBox: {
      x: -24,
      y: -24,
      width: 48,
      height: 48,
    },
    pins: [
      {
        name: "D",
        role: "drain",
        at: {
          x: 10,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "G",
        role: "gate",
        at: {
          x: -20,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S",
        role: "source",
        at: {
          x: 10,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "B",
        role: "bulk",
        at: {
          x: 20,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: -6.976744,
          },
          {
            x: 10,
            y: -6.976744,
          },
          {
            x: 10,
            y: -20,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: 6.976744,
          },
          {
            x: 10,
            y: 6.976744,
          },
          {
            x: 10,
            y: 20,
          },
        ],
        part: "source-arrow-host",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -11.802326,
            y: -9.593023,
          },
          {
            x: -11.802326,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: -9.593023,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "polygon",
        points: [
          {
            x: -6.569767,
            y: -12.5,
          },
          {
            x: -6.569767,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: -12.5,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "line",
        from: {
          x: -8.895349,
          y: 0,
        },
        to: {
          x: -20,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -3.662791,
          y: 0,
        },
        to: {
          x: 10,
          y: 0,
        },
        part: "bulk-lead",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 16.395349,
          y: 0,
        },
        to: {
          x: 20,
          y: 0,
        },
        part: "bulk-lead",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: 10,
            y: 0,
          },
          {
            x: 16.395349,
            y: -3.488372,
          },
          {
            x: 16.395349,
            y: 3.488372,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "bulk-lead",
      },
    ],
    variants: [
      {
        id: "textbook-3terminal",
        hiddenPinNames: ["B"],
        hiddenPrimitiveParts: ["bulk-lead", "source-arrow-host"],
        additionalPrimitives: [
          {
            kind: "polyline",
            points: [
              {
                x: -3.662791,
                y: 6.976744,
              },
              {
                x: 10,
                y: 6.976744,
              },
              {
                x: 10,
                y: 20,
              },
            ],
            part: "source-arrow",
            style: {
              strokeRole: "normal",
              lineCap: "butt",
              lineJoin: "miter",
            },
          },
          {
            kind: "polygon",
            points: [
              {
                x: 10.581395,
                y: 6.976744,
              },
              {
                x: 1.27907,
                y: 2.906977,
              },
              {
                x: 1.27907,
                y: 11.046512,
              },
            ],
            fill: "foreground",
            stroke: "none",
            part: "source-arrow",
          },
        ],
      },
    ],
    aliases: ["mos-n"],
  },
  {
    schemaVersion: 1,
    id: "nmos3",
    name: "NMOS (3-terminal)",
    viewBox: {
      x: -24,
      y: -24,
      width: 39,
      height: 48,
    },
    pins: [
      {
        name: "D",
        role: "drain",
        at: {
          x: 10,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "G",
        role: "gate",
        at: {
          x: -20,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S",
        role: "source",
        at: {
          x: 10,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: -6.976744,
          },
          {
            x: 10,
            y: -6.976744,
          },
          {
            x: 10,
            y: -20,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -11.802326,
            y: -9.593023,
          },
          {
            x: -11.802326,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: -9.593023,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "polygon",
        points: [
          {
            x: -6.569767,
            y: -12.5,
          },
          {
            x: -6.569767,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: -12.5,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "line",
        from: {
          x: -8.895349,
          y: 0,
        },
        to: {
          x: -20,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -3.662791,
            y: 6.976744,
          },
          {
            x: 10,
            y: 6.976744,
          },
          {
            x: 10,
            y: 20,
          },
        ],
        part: "source-arrow",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: 10.581395,
            y: 6.976744,
          },
          {
            x: 1.27907,
            y: 2.906977,
          },
          {
            x: 1.27907,
            y: 11.046512,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "source-arrow",
      },
    ],
    variants: [],
    aliases: ["mos-n-3"],
  },
  {
    schemaVersion: 1,
    id: "npn",
    name: "NPN Bipolar Transistor",
    viewBox: {
      x: -34,
      y: -34,
      width: 42,
      height: 68,
    },
    pins: [
      {
        name: "C",
        role: "collector",
        at: {
          x: 0,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "B",
        role: "base",
        at: {
          x: -30,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
      {
        name: "E",
        role: "emitter",
        at: {
          x: 0,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -30,
          y: 0,
        },
        to: {
          x: -9,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -9,
          y: -13,
        },
        to: {
          x: -9,
          y: 13,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -9,
          y: -8,
        },
        to: {
          x: 0,
          y: -16,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -16,
        },
        to: {
          x: 0,
          y: -30,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -9,
          y: 8,
        },
        to: {
          x: 0,
          y: 16,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: 16,
        },
        to: {
          x: 0,
          y: 30,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -1,
            y: 15.2,
          },
          {
            x: -6.2,
            y: 8.8,
          },
          {
            x: -0.2,
            y: 9.8,
          },
        ],
        fill: "foreground",
        stroke: "none",
      },
    ],
    variants: [],
    aliases: ["bjt-npn", "bipolar-npn"],
  },
  {
    schemaVersion: 1,
    id: "opamp",
    name: "Operational Amplifier",
    viewBox: {
      x: -54,
      y: -28,
      width: 98,
      height: 56,
    },
    pins: [
      {
        name: "IN+",
        role: "non-inverting-input",
        at: {
          x: -50,
          y: 10,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
      {
        name: "IN-",
        role: "inverting-input",
        at: {
          x: -50,
          y: -10,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
      {
        name: "OUT",
        role: "output",
        at: {
          x: 40,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -50,
          y: -10,
        },
        to: {
          x: -26.952962,
          y: -10,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -50,
          y: 10,
        },
        to: {
          x: -26.797909,
          y: 10,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 23.202091,
          y: 0,
        },
        to: {
          x: 40,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "path",
        data: "M -26.7979 -24.9983 L -26.7979 25 L 23.2021 0 Z",
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
          miterLimit: 4,
        },
      },
      {
        kind: "line",
        from: {
          x: -18.047038,
          y: 8.749129,
        },
        to: {
          x: -18.047038,
          y: 16.249129,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -21.796167,
          y: 12.5,
        },
        to: {
          x: -14.296167,
          y: 12.5,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -21.796167,
          y: -12.5,
        },
        to: {
          x: -14.296167,
          y: -12.5,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: ["op-amp", "operational-amplifier"],
  },
  {
    schemaVersion: 1,
    id: "pmos",
    name: "PMOS",
    viewBox: {
      x: -24,
      y: -24,
      width: 48,
      height: 48,
    },
    pins: [
      {
        name: "D",
        role: "drain",
        at: {
          x: 10,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "G",
        role: "gate",
        at: {
          x: -20,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S",
        role: "source",
        at: {
          x: 10,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "B",
        role: "bulk",
        at: {
          x: 20,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: 6.976744,
          },
          {
            x: 10,
            y: 6.976744,
          },
          {
            x: 10,
            y: 20,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: -6.976744,
          },
          {
            x: 10,
            y: -6.976744,
          },
          {
            x: 10,
            y: -20,
          },
        ],
        part: "source-arrow-host",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -11.802326,
            y: -9.593023,
          },
          {
            x: -11.802326,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: -9.593023,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "polygon",
        points: [
          {
            x: -6.569767,
            y: -12.5,
          },
          {
            x: -6.569767,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: -12.5,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "line",
        from: {
          x: -8.895349,
          y: 0,
        },
        to: {
          x: -20,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -3.662791,
          y: 0,
        },
        to: {
          x: 13.604651,
          y: 0,
        },
        part: "bulk-lead",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: 20,
            y: 0,
          },
          {
            x: 13.604651,
            y: -3.77907,
          },
          {
            x: 13.604651,
            y: 3.77907,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "bulk-lead",
      },
    ],
    variants: [
      {
        id: "textbook-3terminal",
        hiddenPinNames: ["B"],
        hiddenPrimitiveParts: ["bulk-lead", "source-arrow-host"],
        additionalPrimitives: [
          {
            kind: "polyline",
            points: [
              {
                x: 5.639535,
                y: -7.122093,
              },
              {
                x: 10,
                y: -7.122093,
              },
              {
                x: 10,
                y: -20,
              },
            ],
            part: "source-arrow",
            style: {
              strokeRole: "normal",
              lineCap: "butt",
              lineJoin: "miter",
            },
          },
          {
            kind: "polygon",
            points: [
              {
                x: -3.662791,
                y: -7.122093,
              },
              {
                x: 5.639535,
                y: -11.19186,
              },
              {
                x: 5.639535,
                y: -3.052326,
              },
            ],
            fill: "foreground",
            stroke: "none",
            part: "source-arrow",
          },
        ],
      },
    ],
    aliases: ["mos-p"],
  },
  {
    schemaVersion: 1,
    id: "pmos3",
    name: "PMOS (3-terminal)",
    viewBox: {
      x: -24,
      y: -24,
      width: 38,
      height: 48,
    },
    pins: [
      {
        name: "D",
        role: "drain",
        at: {
          x: 10,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "G",
        role: "gate",
        at: {
          x: -20,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S",
        role: "source",
        at: {
          x: 10,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "polyline",
        points: [
          {
            x: -4.244186,
            y: 6.976744,
          },
          {
            x: 10,
            y: 6.976744,
          },
          {
            x: 10,
            y: 20,
          },
        ],
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -11.802326,
            y: -9.593023,
          },
          {
            x: -11.802326,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: 9.593023,
          },
          {
            x: -8.895349,
            y: -9.593023,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "polygon",
        points: [
          {
            x: -6.569767,
            y: -12.5,
          },
          {
            x: -6.569767,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: 12.5,
          },
          {
            x: -3.662791,
            y: -12.5,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "gate-bar",
      },
      {
        kind: "line",
        from: {
          x: -8.895349,
          y: 0,
        },
        to: {
          x: -20,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: 5.639535,
            y: -7.122093,
          },
          {
            x: 10,
            y: -7.122093,
          },
          {
            x: 10,
            y: -20,
          },
        ],
        part: "source-arrow",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -3.662791,
            y: -7.122093,
          },
          {
            x: 5.639535,
            y: -11.19186,
          },
          {
            x: 5.639535,
            y: -3.052326,
          },
        ],
        fill: "foreground",
        stroke: "none",
        part: "source-arrow",
      },
    ],
    variants: [],
    aliases: ["mos-p-3"],
  },
  {
    schemaVersion: 1,
    id: "pnp",
    name: "PNP Bipolar Transistor",
    viewBox: {
      x: -34,
      y: -34,
      width: 42,
      height: 68,
    },
    pins: [
      {
        name: "C",
        role: "collector",
        at: {
          x: 0,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "B",
        role: "base",
        at: {
          x: -30,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
      {
        name: "E",
        role: "emitter",
        at: {
          x: 0,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -30,
          y: 0,
        },
        to: {
          x: -9,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -9,
          y: -13,
        },
        to: {
          x: -9,
          y: 13,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -9,
          y: -8,
        },
        to: {
          x: 0,
          y: -16,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -16,
        },
        to: {
          x: 0,
          y: -30,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -9,
          y: 8,
        },
        to: {
          x: 0,
          y: 16,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: 16,
        },
        to: {
          x: 0,
          y: 30,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -6.2,
            y: 8.8,
          },
          {
            x: -1,
            y: 15.2,
          },
          {
            x: -8.5,
            y: 14.2,
          },
        ],
        fill: "foreground",
        stroke: "none",
      },
    ],
    variants: [],
    aliases: ["bjt-pnp", "bipolar-pnp"],
  },
  {
    schemaVersion: 1,
    id: "port",
    name: "Port",
    viewBox: {
      x: -14,
      y: -7,
      width: 28,
      height: 14,
    },
    pins: [
      {
        name: "P",
        role: "port",
        at: {
          x: 10,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "circle",
        center: {
          x: -7.086614,
          y: 0,
        },
        radius: 2.47907,
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 10,
          y: 0,
        },
        to: {
          x: -4.607544,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: [],
  },
  {
    schemaVersion: 1,
    id: "port-filled",
    name: "Filled Port",
    viewBox: {
      x: -14,
      y: -7,
      width: 28,
      height: 14,
    },
    pins: [
      {
        name: "P",
        role: "port",
        at: {
          x: 10,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "circle",
        center: {
          x: -7.086614,
          y: 0,
        },
        radius: 2.47907,
        fill: "foreground",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 10,
          y: 0,
        },
        to: {
          x: -4.607544,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: ["solid-port"],
  },
  {
    schemaVersion: 1,
    id: "resistor",
    name: "Resistor",
    viewBox: {
      x: -10,
      y: -24,
      width: 20,
      height: 48,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: 0,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 0,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "path",
        data: "M 0 -20 L 0 -8.72093 L 5.372093 -6.395349 L -4.604651 -4.069767 L 5.372093 -1.162791 L -4.988372 1.744186 L 5.372093 4.651163 L -4.604651 7.55814 L 0 8.72093 L 0 20",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
          miterLimit: 12,
        },
      },
    ],
    variants: [],
    aliases: [],
  },
  {
    schemaVersion: 1,
    id: "transformer",
    name: "Transformer / Coupled Inductor",
    viewBox: {
      x: -34,
      y: -34,
      width: 68,
      height: 68,
    },
    pins: [
      {
        name: "P1",
        role: "primary",
        at: {
          x: -20,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "P2",
        role: "primary",
        at: {
          x: -20,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S1",
        role: "secondary",
        at: {
          x: 20,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S2",
        role: "secondary",
        at: {
          x: 20,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "path",
        data: "M -20 -30 L -20 -22 C -30 -19 -30 -11 -20 -8 C -10 -5 -10 3 -20 6 C -30 9 -30 17 -20 20 L -20 30",
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "path",
        data: "M 20 -30 L 20 -22 C 10 -19 10 -11 20 -8 C 30 -5 30 3 20 6 C 10 9 10 17 20 20 L 20 30",
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -4,
          y: -20,
        },
        to: {
          x: -4,
          y: 20,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 4,
          y: -20,
        },
        to: {
          x: 4,
          y: 20,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: ["coupled-inductor", "magnetic-transformer"],
  },
  {
    schemaVersion: 1,
    id: "vccs",
    name: "Voltage-Controlled Current Source",
    viewBox: {
      x: -34,
      y: -34,
      width: 64,
      height: 68,
    },
    pins: [
      {
        name: "OUT+",
        role: "output-positive",
        at: {
          x: 20,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "OUT-",
        role: "output-negative",
        at: {
          x: 20,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "CTRL+",
        role: "control-positive",
        at: {
          x: -30,
          y: -10,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
      {
        name: "CTRL-",
        role: "control-negative",
        at: {
          x: -30,
          y: 10,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: 20,
          y: -30,
        },
        to: {
          x: 20,
          y: -12,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "circle",
        center: {
          x: 20,
          y: 0,
        },
        radius: 12,
        fill: "none",
        stroke: "foreground",
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 20,
          y: 12,
        },
        to: {
          x: 20,
          y: 30,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -30,
          y: -10,
        },
        to: {
          x: -12,
          y: -10,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -30,
          y: 10,
        },
        to: {
          x: -12,
          y: 10,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -9,
          y: -13,
        },
        to: {
          x: -9,
          y: -7,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -12,
          y: -10,
        },
        to: {
          x: -6,
          y: -10,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -12,
          y: 10,
        },
        to: {
          x: -6,
          y: 10,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 20,
          y: -6,
        },
        to: {
          x: 20,
          y: 5,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: 20,
            y: 8,
          },
          {
            x: 15.5,
            y: 1,
          },
          {
            x: 24.5,
            y: 1,
          },
        ],
        fill: "foreground",
        stroke: "none",
      },
    ],
    variants: [],
    aliases: ["dependent-current-source", "transconductance-source"],
  },
  {
    schemaVersion: 1,
    id: "vdd",
    name: "VDD Power Port",
    viewBox: {
      x: -12,
      y: -2,
      width: 24,
      height: 26,
    },
    pins: [
      {
        name: "P",
        role: "power",
        at: {
          x: 0,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: 0,
          y: 20,
        },
        to: {
          x: 0,
          y: 2.5,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -10,
            y: -0.88,
          },
          {
            x: 10,
            y: -0.88,
          },
          {
            x: 10,
            y: 2.36,
          },
          {
            x: -10,
            y: 2.36,
          },
        ],
        fill: "foreground",
        stroke: "none",
      },
    ],
    variants: [],
    aliases: ["power-vdd", "vpwr"],
    labelVisibility: "hidden",
  },
  {
    schemaVersion: 1,
    id: "voltage-amplifier",
    name: "Voltage Amplifier",
    viewBox: {
      x: -44,
      y: -28,
      width: 88,
      height: 56,
    },
    pins: [
      {
        name: "IN",
        role: "input",
        at: {
          x: -40,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
      {
        name: "OUT",
        role: "output",
        at: {
          x: 40,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 20,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -40,
          y: 0,
        },
        to: {
          x: -22,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "path",
        data: "M -22 -24 L -22 24 L 22 0 Z",
        style: {
          strokeRole: "emphasis",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 22,
          y: 0,
        },
        to: {
          x: 40,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: ["gain-block", "voltage-gain", "a0"],
  },
  {
    schemaVersion: 1,
    id: "voltage-source",
    name: "Independent Voltage Source",
    viewBox: {
      x: -24,
      y: -24,
      width: 39,
      height: 48,
    },
    pins: [
      {
        name: "+",
        role: "positive",
        at: {
          x: 0,
          y: -20,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "-",
        role: "negative",
        at: {
          x: 0,
          y: 20,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "circle",
        center: {
          x: 0,
          y: 0,
        },
        radius: 10.755814,
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -20.058139,
          y: -14.534884,
        },
        to: {
          x: -11.918605,
          y: -14.534884,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -15.988372,
          y: -18.604651,
        },
        to: {
          x: -15.988372,
          y: -10.465117,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: -20.058139,
          y: 13.372093,
        },
        to: {
          x: -11.918605,
          y: 13.372093,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -10.755814,
        },
        to: {
          x: 0,
          y: -20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: 10.755814,
        },
        to: {
          x: 0,
          y: 20,
        },
        style: {
          strokeRole: "normal",
          lineCap: "butt",
          lineJoin: "miter",
        },
      },
    ],
    variants: [],
    aliases: ["dc-voltage"],
  },
];
