// Generated by scripts/generate-razavi-symbol-catalog.mjs. Do not edit.
import type { SymbolDefinition } from "./schema.js";
import type {
  RazaviSemanticPrimitiveEntry,
  RazaviSymbolCatalogEntry,
} from "./razavi-catalog.js";

export const razaviSymbolCatalogIdentity = {
  schemaVersion: 1,
  id: "razavi-symbols",
  version: 1,
  decoder: {
    id: "icm-vss-master-ir",
    version: "0.1.0",
  },
} as const;

export const razaviSymbolCatalogEntries: readonly RazaviSymbolCatalogEntry[] = [
  {
    symbolId: "nmos",
    name: "NMOS",
    category: "transistor",
    source: {
      stencilHash:
        "502f574ae7527aa530502d401f7cd490de296593f4fefc61eb306c084e6f3587",
      masterNameU: "NMOS4",
      decoderVersion: "0.1.0",
    },
    reviewStatus: "reviewed",
    pinOrder: ["D", "G", "S", "B"],
    palette: true,
    automaticMappings: ["spice:M:nmos", "pdk:model-type:nmos"],
    assetPath: "nmos.symbol.json",
    assetHash:
      "8b0a28ddc9041501287c42c3808bbf70ec7c087ee9f2404f87e95473f3b63fb3",
  },
  {
    symbolId: "pmos3",
    name: "PMOS (3-terminal)",
    category: "transistor",
    source: {
      stencilHash:
        "502f574ae7527aa530502d401f7cd490de296593f4fefc61eb306c084e6f3587",
      masterNameU: "Pmos3.a",
      decoderVersion: "0.1.0",
    },
    reviewStatus: "provisional",
    pinOrder: ["D", "G", "S"],
    palette: true,
    automaticMappings: [],
    assetPath: "pmos3.symbol.json",
    assetHash:
      "e7f4281417f841c611d25c48380c6f2437613c729a1c5d4d00af2725c295deff",
  },
  {
    symbolId: "resistor",
    name: "Resistor",
    category: "passive",
    source: {
      stencilHash:
        "502f574ae7527aa530502d401f7cd490de296593f4fefc61eb306c084e6f3587",
      masterNameU: "R",
      decoderVersion: "0.1.0",
    },
    reviewStatus: "reviewed",
    pinOrder: ["1", "2"],
    palette: true,
    automaticMappings: ["spice:R"],
    assetPath: "resistor.symbol.json",
    assetHash:
      "503b6522cf40d53de5dd8d12e1a86a0c84fb957212458694848e0aa17a38e8da",
  },
  {
    symbolId: "voltage-source",
    name: "Independent Voltage Source",
    category: "source",
    source: {
      stencilHash:
        "502f574ae7527aa530502d401f7cd490de296593f4fefc61eb306c084e6f3587",
      masterNameU: "DC-V",
      decoderVersion: "0.1.0",
    },
    reviewStatus: "reviewed",
    pinOrder: ["+", "-"],
    palette: true,
    automaticMappings: ["spice:V"],
    assetPath: "voltage-source.symbol.json",
    assetHash:
      "69f7cc7a9a0759d1ee9b712fa254d13d738e0b42bb0fec7b4eee1deaacd121f4",
  },
];

export const razaviSemanticPrimitives: readonly RazaviSemanticPrimitiveEntry[] =
  [
    {
      id: "junction-dot",
      disposition: "semantic-primitive",
      source: {
        stencilHash:
          "502f574ae7527aa530502d401f7cd490de296593f4fefc61eb306c084e6f3587",
        masterNameU: "node",
        decoderVersion: "0.1.0",
      },
      geometry: {
        kind: "circle",
        sourceDiameterIU: 0.0787401574803157,
        fill: "foreground",
        stroke: "none",
      },
      runtimeOwner: "presentation.nodes.junction",
    },
  ];

export const razaviCatalogSymbols: readonly SymbolDefinition[] = [
  {
    schemaVersion: 1,
    id: "nmos",
    name: "NMOS",
    viewBox: {
      x: -30,
      y: -30,
      width: 60,
      height: 60,
    },
    pins: [
      {
        name: "D",
        role: "drain",
        at: {
          x: 20,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "G",
        role: "gate",
        at: {
          x: -30,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S",
        role: "source",
        at: {
          x: 20,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "B",
        role: "bulk",
        at: {
          x: 30,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -30,
          y: 0,
        },
        to: {
          x: -17,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -17,
          y: -14,
        },
        to: {
          x: -17,
          y: 14,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -10,
          y: -20,
        },
        to: {
          x: -10,
          y: 20,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -10,
          y: -14,
        },
        to: {
          x: 20,
          y: -14,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: 20,
          y: -30,
        },
        to: {
          x: 20,
          y: -14,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -10,
          y: 14,
        },
        to: {
          x: 20,
          y: 14,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: 20,
          y: 14,
        },
        to: {
          x: 20,
          y: 30,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -10,
          y: 0,
        },
        to: {
          x: 30,
          y: 0,
        },
        part: "bulk-lead",
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: -2,
            y: 0,
          },
          {
            x: 7,
            y: -5,
          },
          {
            x: 7,
            y: 5,
          },
        ],
        fill: "foreground",
        part: "bulk-lead",
      },
    ],
    variants: [
      {
        id: "textbook-3terminal",
        hiddenPinNames: ["B"],
        hiddenPrimitiveParts: ["bulk-lead"],
        additionalPrimitives: [
          {
            kind: "polygon",
            points: [
              {
                x: 10,
                y: 14,
              },
              {
                x: 2,
                y: 10,
              },
              {
                x: 4,
                y: 19,
              },
            ],
            fill: "foreground",
            part: "source-arrow",
          },
        ],
      },
    ],
    aliases: ["mos-n"],
  },
  {
    schemaVersion: 1,
    id: "pmos3",
    name: "PMOS (3-terminal)",
    viewBox: {
      x: -30,
      y: -30,
      width: 60,
      height: 60,
    },
    pins: [
      {
        name: "D",
        role: "drain",
        at: {
          x: 20,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "G",
        role: "gate",
        at: {
          x: -30,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "S",
        role: "source",
        at: {
          x: 20,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -30,
          y: 0,
        },
        to: {
          x: -17,
          y: 0,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -17,
          y: -14,
        },
        to: {
          x: -17,
          y: 14,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -10,
          y: -20,
        },
        to: {
          x: -10,
          y: 20,
        },
        style: {
          strokeRole: "emphasis",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -10,
          y: -14,
        },
        to: {
          x: 20,
          y: -14,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: 20,
          y: -30,
        },
        to: {
          x: 20,
          y: -14,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: -10,
          y: 14,
        },
        to: {
          x: 20,
          y: 14,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "line",
        from: {
          x: 20,
          y: 14,
        },
        to: {
          x: 20,
          y: 30,
        },
        style: {
          strokeRole: "normal",
          lineCap: "round",
          lineJoin: "round",
        },
      },
      {
        kind: "polygon",
        points: [
          {
            x: 2,
            y: -14,
          },
          {
            x: 10,
            y: -10,
          },
          {
            x: 8,
            y: -19,
          },
        ],
        fill: "foreground",
        part: "source-arrow",
      },
    ],
    variants: [],
    aliases: ["mos-p-3"],
  },
  {
    schemaVersion: 1,
    id: "resistor",
    name: "Resistor",
    viewBox: {
      x: -30,
      y: -15,
      width: 60,
      height: 30,
    },
    pins: [
      {
        name: "1",
        role: "passive",
        at: {
          x: -30,
          y: 0,
        },
        direction: "west",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "2",
        role: "passive",
        at: {
          x: 30,
          y: 0,
        },
        direction: "east",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: -30,
          y: 0,
        },
        to: {
          x: -20,
          y: 0,
        },
      },
      {
        kind: "polyline",
        points: [
          {
            x: -20,
            y: 0,
          },
          {
            x: -15,
            y: -8,
          },
          {
            x: -5,
            y: 8,
          },
          {
            x: 5,
            y: -8,
          },
          {
            x: 15,
            y: 8,
          },
          {
            x: 20,
            y: 0,
          },
        ],
      },
      {
        kind: "line",
        from: {
          x: 20,
          y: 0,
        },
        to: {
          x: 30,
          y: 0,
        },
      },
    ],
    variants: [],
    aliases: [],
  },
  {
    schemaVersion: 1,
    id: "voltage-source",
    name: "Independent Voltage Source",
    viewBox: {
      x: -18,
      y: -30,
      width: 36,
      height: 60,
    },
    pins: [
      {
        name: "+",
        role: "positive",
        at: {
          x: 0,
          y: -30,
        },
        direction: "north",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
      {
        name: "-",
        role: "negative",
        at: {
          x: 0,
          y: 30,
        },
        direction: "south",
        presentation: {
          visibility: "visible",
          leadLength: 10,
        },
      },
    ],
    primitives: [
      {
        kind: "line",
        from: {
          x: 0,
          y: -30,
        },
        to: {
          x: 0,
          y: -15,
        },
      },
      {
        kind: "circle",
        center: {
          x: 0,
          y: 0,
        },
        radius: 15,
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: 15,
        },
        to: {
          x: 0,
          y: 30,
        },
      },
      {
        kind: "line",
        from: {
          x: -5,
          y: -6,
        },
        to: {
          x: 5,
          y: -6,
        },
      },
      {
        kind: "line",
        from: {
          x: 0,
          y: -11,
        },
        to: {
          x: 0,
          y: -1,
        },
      },
      {
        kind: "line",
        from: {
          x: -5,
          y: 7,
        },
        to: {
          x: 5,
          y: 7,
        },
      },
    ],
    variants: [],
    aliases: ["dc-voltage"],
  },
];
